## Lab 3: pandas

#### Introduction

We will examine a dataset containing characteristics of lego sets manufactured between 1961 and 2019 from the BRICKSET website. Variables in the dataset are described below.

| VARIABLE             |      DESCRIPTION             |
|:----------|:-------------|
| ID |  set id |
| Name |    name of set   |
| Themegroup | themegroup of set |
| Theme |  theme of set |
| Subtheme |    subtheme of set   |
| Year | year released |
| Pieces |  number of pieces |
| Minifig |    number of minifigs   |
| Package | type of packaging |
| Retail_Price |  recommended retail pri



Load pandas to read in the data and save it as dataframe named lego.

## Student Name: Noor Ali Alawlaqi - S21107270

In [8]:
import pandas as pd

lego = pd.read_csv('lego.csv')
lego.head()

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
0,100STORES-1,100 Stores minifigure,Miscellaneous,Promotional,LEGO brand stores,2019.0,NaN,0,Blister pack,NaN
1,10264-1,Corner Garage,Model making,Creator Expert,Modular Buildings,2019.0,2569.0,6,Box,199.99
2,10265-1,Ford Mustang,Model making,Creator Expert,Vehicles,2019.0,1471.0,0,Box,149.99
3,10766-1,Woody & RC,Licensed,Toy Story,Toy Story 4,2019.0,69.0,0,Box,9.99
4,10769-1,RV Vacation,Licensed,Toy Story,Toy Story 4,2019.0,178.0,0,Box,34.99

#### Question 1:
Some sets have missing information for retail_price or pieces or both. This could be because the sets are free (giveaways), they aren’t traditional lego sets (comic books, etc) or just because the information is missing. Filter the lego dataset based on the specifications below and save the result as lego. Hence, you will overwrite the original lego object. In addition, describe the implications of removing these sets.

Your new lego (data frame) should have:

• no missing pieces

• only contain sets with a nonzero number of pieces

• no missing retail_price

• only contain sets with a nonzero retail_price

• no missing year

- Print out the shape of the dataframe after cleaning the dataset.
-

In [40]:
# Write your answer here
print(lego.shape)
lego2 = lego.dropna()
print(lego2.shape)
lego2 = lego2.loc[lego2.retail_price>0,:]
lego2 = lego2.loc[lego2.pieces>0,:]
print(lego2.shape)
lego2.head()

(12214, 10)
(4360, 10)
(4277, 10)

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1,10264-1,Corner Garage,Model making,Creator Expert,Modular Buildings,2019.0,2569.0,6,Box,199.99
2,10265-1,Ford Mustang,Model making,Creator Expert,Vehicles,2019.0,1471.0,0,Box,149.99
3,10766-1,Woody & RC,Licensed,Toy Story,Toy Story 4,2019.0,69.0,0,Box,9.99
4,10769-1,RV Vacation,Licensed,Toy Story,Toy Story 4,2019.0,178.0,0,Box,34.99
5,10770-1,Buzz & Woody's Carnival Mania!,Licensed,Toy Story,Toy Story 4,2019.0,230.0,0,Box,49.99

#### Question 2:	
Arrange the dataset in descending order of retail_price and print the first three rows. Report in words the names of the three most expensive lego sets, their prices, and how many pieces each has.

In [43]:
# Write your answer here
lego2.sort_values(by='retail_price', ascending=False).head()

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price
1434,75192-1,Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2017.0,7541.0,8,Box,799.99
5944,10179-1,Ultimate Collector's Millennium Falcon,Licensed,Star Wars,Ultimate Collector Series,2007.0,5197.0,5,Box,499.99
2065,75159-1,Death Star,Licensed,Star Wars,Ultimate Collector Series,2016.0,4016.0,27,Box,499.99
771,71043-1,Hogwarts Castle,Licensed,Wizarding World,Harry Potter,2018.0,6020.0,28,Box,399.99
4444,10221-1,Super Star Destroyer,Licensed,Star Wars,Ultimate Collector Series,2011.0,3152.0,5,Box,399.99

#### Question 3:

It appears that the most expensive sets generally have more pieces. Create a new variable (column) price_per_piece, representing the price in dollars per piece for each of the sets. Save the result as lego2. Hence, you will overwrite the current lego object.

In [46]:
# Write your answer here
lego2['price_per_piece']= lego2.retail_price / lego2.pieces
lego2.sort_values(by='price_per_piece', ascending=False).head()

,id,name,themegroup,theme,subtheme,year,pieces,minifigs,package,retail_price,price_per_piece
5551,8878-1,Rechargeable Battery Box,Technical,Power Functions,Accessories,2009.0,1.0,0,Polybag,49.99,49.990
5553,8887-1,Transformer 10V DC,Technical,Power Functions,Accessories,2009.0,1.0,0,Polybag,29.99,29.990
5616,COMCON005-1,Collectable Display Set 2,Licensed,Star Wars,Miscellaneous,2009.0,2.0,3,Plastic box,49.99,24.995
8694,9755-1,Temperature Sensor,Technical,Mindstorms,1.0,1999.0,1.0,0,Polybag,24.00,24.000
7540,3805-1,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.5,2001.0,1.0,0,Other,20.00,20.000

#### Question 4:	

Arrange the lego2 dataset in descending order of price_per_piece and return only the columns: name, themegroup, theme, pieces, price_per_piece, and the first five rows. What do you notice about these sets?

In [49]:
# Write your answer here
lego2.sort_values(by='price_per_piece', ascending=False).loc[:,['name', 'themegroup', 'theme', 'pieces', 'price_per_piece']].head()

,name,themegroup,theme,pieces,price_per_piece
5551,Rechargeable Battery Box,Technical,Power Functions,1.0,49.990
5553,Transformer 10V DC,Technical,Power Functions,1.0,29.990
5616,Collectable Display Set 2,Licensed,Star Wars,2.0,24.995
8694,Temperature Sensor,Technical,Mindstorms,1.0,24.000
7540,Robotics Invention System Upgrade Kit,Technical,Mindstorms,1.0,20.000

#### Question 5:

What is the mean price_per_piece for the top 40 'Toy Story' sets in terms of price_per_piece?

In [52]:
# Write your answer here
lego3 = lego2.sort_values(by='price_per_piece', ascending=False)
lego3.loc[lego3.theme == 'Toy Story',:].head(40).price_per_piece.mean()

0.16089862892544177

#### Question 6:

What are the unique themes in the lego dataset?

In [55]:
# Write your answer here
lego2.theme.value_counts()

theme
Star Wars                            498
Collectable Minifigures              431
City                                 390
Town                                 310
Racers                               183
                                    ...
The Lego Movie 2: The Second Part      2
Explore                                1
Bricks and More                        1
Books                                  1
LEGOLAND                               1
Name: count, Length: 73, dtype: int64